const QUESTIONS = [
{category:"General Topics Related to Asbestos",q:"Which statement best describes asbestos?",a:["A synthetic plastic fiber","A naturally occurring group of fibrous minerals","A type of fiberglass insulation","A chemical added to concrete"],correct:1,explanation:"Asbestos is a naturally occurring group of fibrous silicate minerals."},
{category:"General Topics Related to Asbestos",q:"Friable asbestos-containing material is material that, when dry:",a:["Cannot release fibers","Can be crumbled, pulverized, or reduced to powder by hand pressure","Contains less than 1% asbestos","Has been painted"],correct:1,explanation:"Friability is based on whether dry material can be crumbled, pulverized, or reduced to powder by hand pressure."},
{category:"General Topics Related to Asbestos",q:"Which is one of the major commercial asbestos fiber types?",a:["Chrysotile","Silicone","Graphite","Cellulose"],correct:0,explanation:"Chrysotile is a major commercial asbestos type."},
{category:"General Topics Related to Asbestos",q:"PACM is an abbreviation for:",a:["Protected asbestos control material","Presumed asbestos-containing material","Permitted asbestos cleanup method","Personal asbestos containment mask"],correct:1,explanation:"PACM means presumed asbestos-containing material."},

{category:"Health and Medical Considerations",q:"Asbestosis primarily involves:",a:["Scarring (fibrosis) of lung tissue","Skin irritation","Hearing loss","Kidney stones"],correct:0,explanation:"Asbestosis is a chronic fibrotic disease of the lungs caused by asbestos exposure."},
{category:"Health and Medical Considerations",q:"Mesothelioma is most strongly associated with cancer of the:",a:["Membranes lining the chest or abdominal cavities","Bones of the hand","Thyroid gland","Outer skin"],correct:0,explanation:"Mesothelioma affects mesothelial linings, commonly the pleura and peritoneum."},
{category:"Health and Medical Considerations",q:"Smoking combined with occupational asbestos exposure:",a:["Eliminates asbestos risk","Can greatly increase lung-cancer risk","Prevents mesothelioma","Only affects the upper airway"],correct:1,explanation:"Smoking and asbestos exposure have a strong combined effect on lung-cancer risk."},
{category:"Health and Medical Considerations",q:"Asbestos-related diseases commonly have:",a:["A long latency period","Symptoms within minutes","No relationship to inhalation","A guaranteed cure"],correct:0,explanation:"Many asbestos diseases develop years or decades after exposure."},
{category:"Health and Medical Considerations",q:"Under the OSHA construction asbestos standard, medical surveillance requirements can be triggered by employees engaged in certain asbestos work or exposure at/above:",a:["The PEL or excursion limit","The noise action level only","50% humidity","Any visible dust of any type"],correct:0,explanation:"OSHA's asbestos construction standard ties medical-surveillance requirements to specified asbestos work and exposure conditions, including the PEL/EL."},

{category:"Personal Protective and Other Equipment",q:"HEPA filters used for asbestos work are designed to remove at least:",a:["50% of 10-micron particles","75% of 5-micron particles","99.97% of 0.3-micron particles","100% of every particle"],correct:2,explanation:"The standard HEPA benchmark is at least 99.97% efficiency for 0.3-micrometer particles."},
{category:"Personal Protective and Other Equipment",q:"A respirator should be selected primarily according to:",a:["Worker preference only","Expected airborne exposure and the protection required","The color of the containment","The building's age"],correct:1,explanation:"Respirator selection must provide adequate protection for the anticipated exposure and task."},
{category:"Personal Protective and Other Equipment",q:"A tight-fitting respirator generally requires:",a:["A fit test","A hard hat sticker","No medical evaluation","A beard for a better seal"],correct:0,explanation:"Tight-fitting respirators require fit testing and a proper face-to-facepiece seal."},
{category:"Personal Protective and Other Equipment",q:"Facial hair that crosses the sealing surface of a tight-fitting respirator:",a:["Improves the seal","Is acceptable with any respirator","Can interfere with the seal and is not permitted","Only matters outdoors"],correct:2,explanation:"Nothing may interfere with the seal of a tight-fitting respirator."},
{category:"Personal Protective and Other Equipment",q:"The main purpose of negative-air equipment in a containment is to:",a:["Heat the work area","Maintain airflow/pressure control and filter exhausted air","Dry ACM quickly","Increase dust generation"],correct:1,explanation:"Negative-air systems help maintain pressure differential and exhaust air through HEPA filtration."},

{category:"Work Practices, Procedures, and Disposal",q:"A basic method for reducing airborne fiber release while disturbing ACM is:",a:["Dry sweeping","Wet methods","Compressed air","High-speed sanding"],correct:1,explanation:"Wet methods are a fundamental engineering/work-practice control for minimizing fiber release."},
{category:"Work Practices, Procedures, and Disposal",q:"Asbestos debris should generally be cleaned using:",a:["Compressed air","Dry broom sweeping","HEPA vacuuming and wet cleaning","A household fan"],correct:2,explanation:"HEPA vacuuming and wet cleaning are standard asbestos cleanup methods; dry sweeping and compressed air are generally prohibited."},
{category:"Work Practices, Procedures, and Disposal",q:"Before asbestos abatement begins, the supervisor should ensure the regulated/work area is:",a:["Accessible to everyone","Properly established, controlled, and posted","Kept under positive pressure","Used as a break room"],correct:1,explanation:"Access control, warning signs and proper work-area preparation are core asbestos controls."},
{category:"Work Practices, Procedures, and Disposal",q:"Asbestos waste leaving the regulated area should be:",a:["Handled to prevent release of fibers and properly contained/labeled","Placed loose in an open truck","Mixed with lunch trash","Allowed to dry before handling"],correct:0,explanation:"ACM waste must be handled, packaged, labeled and transported in a manner that prevents fiber release and meets applicable requirements."},
{category:"Work Practices, Procedures, and Disposal",q:"Why are critical barriers installed during many containment setups?",a:["To increase ventilation from occupied areas","To isolate openings and help prevent fiber migration","To store respirators","To provide natural lighting"],correct:1,explanation:"Critical barriers seal openings and help isolate the asbestos work area."},
{category:"Work Practices, Procedures, and Disposal",q:"Which practice is generally prohibited for asbestos cleanup?",a:["HEPA vacuuming","Wet wiping","Dry sweeping","Careful waste bagging"],correct:2,explanation:"Dry sweeping can re-aerosolize asbestos fibers and is prohibited."},
{category:"Work Practices, Procedures, and Disposal",q:"When a glove bag is used for appropriate asbestos work, it should be:",a:["Used without controls because it is automatically safe","Used according to applicable OSHA procedures and kept intact","Filled with compressed air","Opened before debris is contained"],correct:1,explanation:"Glove-bag operations have specific work-practice requirements; integrity and controlled procedures are essential."},
{category:"Work Practices, Procedures, and Disposal",q:"A decontamination system is intended primarily to:",a:["Prevent asbestos contamination from being carried out of the regulated area","Increase worker production speed","Store waste indefinitely","Replace respiratory protection"],correct:0,explanation:"Decontamination procedures limit migration of asbestos contamination to clean areas."},
{category:"Work Practices, Procedures, and Disposal",q:"The preferred condition for ACM during removal is generally:",a:["Adequately wet, unless a specific exception applies","Bone dry","Heated until brittle","Ground into powder"],correct:0,explanation:"Adequately wet methods are a primary fiber-control requirement, subject to specific regulatory exceptions."},
{category:"Work Practices, Procedures, and Disposal",q:"After gross removal, final cleaning should focus on:",a:["Leaving visible debris for the inspector","Removing visible residue and contamination using approved cleaning methods","Dry dusting all surfaces","Turning off controls immediately"],correct:1,explanation:"Thorough cleaning is required before the work area can progress toward clearance/reoccupancy procedures."},
{category:"Work Practices, Procedures, and Disposal",q:"Which is the best reason to maintain containment integrity throughout abatement?",a:["To prevent fiber migration outside the controlled area","To increase room temperature","To reduce lighting costs","To make ACM dry faster"],correct:0,explanation:"Containment integrity is essential for preventing contamination of adjacent areas."},
{category:"Work Practices, Procedures, and Disposal",q:"New Jersey asbestos-abatement employers generally must submit written notification of intent at least:",a:["24 hours before work","3 calendar days before work","10 calendar days before work","30 calendar days before work"],correct:2,explanation:"NJ LWD states that employers planning asbestos work must submit written notification at least 10 calendar days before beginning work."},

{category:"Additional Safety Hazards",q:"Besides asbestos exposure, a supervisor should evaluate hazards such as:",a:["Electrical hazards, falls, heat stress and confined spaces","Only asbestos fibers","Only noise","Only weather"],correct:0,explanation:"Asbestos projects can involve numerous conventional construction and occupational hazards."},
{category:"Additional Safety Hazards",q:"Water used for wet methods can create an increased risk of:",a:["Electrical shock around energized equipment","Radiation exposure","UV burns indoors","Magnetic fields"],correct:0,explanation:"Wet methods can create electrical hazards; electrical safety must be incorporated into planning."},
{category:"Additional Safety Hazards",q:"Wearing protective clothing and respirators can contribute to:",a:["Heat stress","Improved hearing","Reduced fall risk automatically","Elimination of fatigue"],correct:0,explanation:"PPE can increase heat load and physical stress."},

{category:"Testing Methodologies",q:"Personal air samples used to assess worker exposure are collected in the worker's:",a:["Breathing zone","Lunch room","Parking lot","Waste dumpster"],correct:0,explanation:"Exposure monitoring uses breathing-zone samples representative of employee exposure."},
{category:"Testing Methodologies",q:"The OSHA asbestos PEL is expressed as an 8-hour:",a:["Time-weighted average","Ceiling temperature","Noise dose","Relative humidity"],correct:0,explanation:"The PEL is an 8-hour time-weighted average airborne concentration."},
{category:"Testing Methodologies",q:"The OSHA asbestos excursion limit is evaluated over:",a:["5 minutes","15 minutes","30 minutes","8 hours"],correct:2,explanation:"The asbestos excursion limit is based on a 30-minute sampling period."},
{category:"Testing Methodologies",q:"The OSHA construction asbestos PEL is:",a:["0.1 fiber per cubic centimeter as an 8-hour TWA","1.0 f/cc as an 8-hour TWA","10 f/cc as an 8-hour TWA","Zero fibers under all circumstances"],correct:0,explanation:"29 CFR 1926.1101 sets the asbestos PEL at 0.1 f/cc as an 8-hour TWA."},
{category:"Testing Methodologies",q:"The OSHA asbestos excursion limit is:",a:["0.1 f/cc over 30 minutes","1.0 f/cc over 30 minutes","5.0 f/cc over 8 hours","10 f/cc over 15 minutes"],correct:1,explanation:"The OSHA asbestos excursion limit is 1.0 f/cc averaged over 30 minutes."},

{category:"Regulations",q:"The OSHA construction asbestos standard is:",a:["29 CFR 1926.1101","29 CFR 1910.1200 only","40 CFR Part 61 only","42 CFR Part 84 only"],correct:0,explanation:"29 CFR 1926.1101 is OSHA's asbestos standard for construction."},
{category:"Regulations",q:"EPA NESHAP asbestos requirements are primarily associated with:",a:["Air-pollution controls for demolition/renovation involving regulated asbestos","Driver licensing","Respirator fit-test brands","Workers' compensation rates"],correct:0,explanation:"The asbestos NESHAP is an EPA air-pollution regulation governing specified demolition/renovation activities and asbestos emissions."},
{category:"Regulations",q:"AHERA is particularly associated with asbestos management in:",a:["Schools","Motor vehicles","Private boats","Restaurants only"],correct:0,explanation:"AHERA established asbestos requirements for public and nonprofit private elementary and secondary schools."},
{category:"Regulations",q:"In New Jersey, an asbestos supervisor permit applicant must pass the approved state examination with at least:",a:["60%","65%","70%","90%"],correct:2,explanation:"New Jersey requires a score of at least 70% on the supervisor examination."},
{category:"Regulations",q:"A person who receives a New Jersey asbestos supervisor permit may:",a:["Perform worker duties without a separate worker permit","Ignore respiratory requirements","Issue NJ employer licenses","Perform any demolition without notification"],correct:0,explanation:"NJ regulations state that a permitted supervisor may perform worker duties without possessing a separate worker permit."},
{category:"Regulations",q:"Which agency issues New Jersey asbestos worker/supervisor permits after required training/examination requirements are met?",a:["NJ Department of Labor and Workforce Development","NJ Motor Vehicle Commission","NJ Treasury only","Local fire department"],correct:0,explanation:"NJ LWD administers the asbestos licensing and worker/supervisor permit program, while NJDOH oversees training and the state examination."},

{category:"Legal Considerations",q:"A supervisor's project records are important because they can:",a:["Document compliance, decisions, monitoring and work practices","Replace all regulatory requirements","Eliminate liability automatically","Be discarded at project completion regardless of requirements"],correct:0,explanation:"Accurate documentation is a key component of regulatory compliance and project accountability."},
{category:"Legal Considerations",q:"Knowingly falsifying asbestos records can:",a:["Create serious regulatory and legal consequences","Improve compliance","Be acceptable if the project is small","Be corrected by deleting all records"],correct:0,explanation:"Required records must be accurate; falsification can result in enforcement and other legal consequences."},
{category:"Legal Considerations",q:"The best response when project conditions differ materially from the approved work plan is to:",a:["Ignore the change","Stop/evaluate as appropriate and address the change under applicable requirements","Hide the condition","Tell workers to improvise without supervision"],correct:1,explanation:"Supervisors should ensure changed conditions are evaluated and handled under applicable plans, specifications and regulatory requirements."},
{category:"Legal Considerations",q:"An asbestos supervisor should treat required records as:",a:["Part of the project's compliance documentation","Optional personal notes","Something only the building owner can see","Unnecessary if no complaint occurs"],correct:0,explanation:"Required records form part of the compliance record and should be maintained as required."},

{category:"Supervisory",q:"A supervisor/competent person's role includes:",a:["Identifying hazards and ensuring required controls are implemented","Only ordering supplies","Only signing time sheets","Delegating all safety responsibility to workers"],correct:0,explanation:"The competent person/supervisor has active responsibilities for hazard recognition, controls, inspections and compliance."},
{category:"Supervisory",q:"If containment is damaged during active abatement, the supervisor's priority is to:",a:["Continue production at all costs","Control the situation and restore required containment/protection","Wait until the end of the shift","Open additional doors"],correct:1,explanation:"Loss of containment can permit fiber migration and requires prompt corrective action."},
{category:"Supervisory",q:"Before assigning a worker to asbestos duties, the supervisor should verify:",a:["Required training, protection and project procedures are in place","Only that the worker owns boots","Only that the worker has construction experience","Nothing if another worker is present"],correct:0,explanation:"Supervisors must ensure personnel are properly trained and protected and understand applicable procedures."}
];