// Original practice questions drawn from public rules; no state examination items.
const OSHA="https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.1101";
const NJ="https://www.nj.gov/labor/safetyandhealth/resources-support/laws-regulations/asbestosact.shtml";
const EPA="https://www.ecfr.gov/current/title-40/chapter-I/subchapter-C/part-61/subpart-M";
const NJDOH="https://www.nj.gov/health/ceohs/asbestos/asbestos-workers-supervisors/";
const RESP="https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.134";
function addQuestions(category,source,rows){
  rows.forEach(([q,a,correct,explanation])=>QUESTIONS.push({category,q,a,correct,explanation,source}));
}
addQuestions("General Topics Related to Asbestos",OSHA,[
["Under OSHA's construction asbestos rule, ACM contains asbestos in what amount?",["More than 1%","Exactly 0.1%","Any detectable trace","More than 50%"],0,"OSHA defines asbestos-containing material as material containing more than one percent asbestos."],
["Which material is generally presumed asbestos-containing in a building constructed no later than 1980?",["Thermal system insulation","New fiberglass batts","Modern vinyl windows","Unpainted steel"],0,"OSHA presumes thermal system insulation in buildings constructed no later than 1980 to be asbestos-containing unless rebutted."],
["What does TSI mean in the asbestos construction standard?",["Thermal system insulation","Testing sample interval","Temporary site inspection","Toxic surface inventory"],0,"TSI means thermal system insulation applied to pipes, fittings, boilers, breeching, tanks, ducts, or other components to prevent heat loss or gain."],
["Which task is Class I asbestos work under OSHA?",["Removing surfacing ACM","Removing asbestos floor tile","Repairing ACM without removal","Vacuuming dust without disturbing ACM"],0,"Class I covers removal of thermal system insulation or surfacing ACM and PACM."],
["Which task is typically Class II asbestos work?",["Removing asbestos floor tile","Removing sprayed surfacing ACM","Only inspecting intact insulation","Painting a clean wall"],0,"Class II removal involves ACM other than thermal system insulation or surfacing material."],
["Class III asbestos work is best described as:",["Repair and maintenance that disturb ACM or PACM","All demolition of an asbestos building","Only transport of asbestos waste","Removal of all surfacing insulation"],0,"Class III is repair and maintenance work where ACM or PACM is likely to be disturbed."],
["An aggressive method of disturbing ACM includes:",["Grinding that disintegrates intact material","Carefully wetting intact material","HEPA vacuuming settled dust","Sealing a clean opening"],0,"OSHA defines aggressive methods as sanding, abrading, grinding, or other methods that break, crumble, or disintegrate intact ACM."],
["Amended water is water with:",["A surfactant to improve penetration","Added bleach to kill spores","A dye to label waste","Extra oxygen for ventilation"],0,"A wetting agent helps water penetrate ACM."]
]);
addQuestions("Health and Medical Considerations",OSHA,[
["Which asbestos-related disease is a fibrotic lung disease rather than a cancer?",["Asbestosis","Mesothelioma","Lung carcinoma","Skin melanoma"],0,"Asbestosis is lung fibrosis associated with asbestos exposure."],
["The primary route of occupational asbestos exposure during abatement is:",["Inhalation of airborne fibers","Absorption through intact skin","Exposure to visible light","Ingestion of drinking water only"],0,"Inhalation of airborne asbestos fibers is the main occupational exposure route."],
["Why is a worker's lack of symptoms a poor basis for judging asbestos exposure?",["Disease can have a long latency","Asbestos causes immediate pain in all cases","Symptoms always disappear after one shift","Medical tests cannot identify any condition"],0,"Asbestos-related diseases may take many years to develop."],
["Under OSHA's construction rule, medical surveillance is required for a worker engaged in Class I, II, or III work for at least:",["30 days per year","One day per year","100 days per year","Every calendar day"],0,"The standard lists 30 or more days per year of Class I, II, or III work as one trigger."],
["OSHA medical surveillance for covered asbestos employees must be provided:",["At no cost to the employee","Only if the worker pays half","Only after a positive disease diagnosis","Only at the end of employment"],0,"The employer must provide required medical examinations without cost to the employee."],
["What health topic should asbestos training address?",["Health effects of asbestos exposure","Only project billing","Only landscaping","Only building paint colors"],0,"OSHA training includes health effects of asbestos exposure."],
["When should a supervisor treat airborne asbestos exposure as a hazard?",["Even when fibers cannot be seen","Only when fibers are visible","Only when workers smell asbestos","Only when the room is warm"],0,"Airborne asbestos fibers can be too small to see; visibility does not establish safe exposure."]
 ,["Why does OSHA require a medical determination for a worker assigned to wear a negative-pressure respirator?",["To ensure the worker is physically able to perform the work and use the equipment","To determine the worker's examination score","To replace a fit test","To decide the building's age"],0,"A physician-supervised determination addresses the worker's physical ability to use a negative-pressure respirator safely."]
]);
addQuestions("Personal Protective and Other Equipment",RESP,[
["Before an employee wears a required respirator, the employer must provide:",["A medical evaluation","A respirator color chart","A dust mask of any type","A paid lunch break"],0,"The respiratory protection standard requires medical evaluation before use."],
["A tight-fitting respirator fit test must be performed:",["Before initial use and at least annually","Only after a worker complains","Once in a career","Only for disposable gloves"],0,"OSHA requires fit testing before initial use, when the facepiece changes, and at least annually."],
["Which condition invalidates a tight-fitting respirator seal?",["Facial hair between sealing surface and face","A clean-shaven face","Proper fit testing","A correctly sized facepiece"],0,"Facial hair between the sealing surface and face is prohibited."],
["A user seal check is performed:",["Each time a tight-fitting respirator is put on","Only during annual fit testing","Only after removing the respirator","Only by the building owner"],0,"Each donning requires a user seal check."],
["Can a user seal check replace a fit test?",["No, both have different purposes","Yes, always","Yes, after one month","Only for negative-air machines"],0,"A seal check is not a substitute for formal fit testing."],
["Which feature is essential to an asbestos HEPA vacuum?",["A HEPA filtration system","An ordinary paper dust bag only","A fan that blows debris outward","An open exhaust port"],0,"A HEPA vacuum is used to capture asbestos dust without releasing it through the exhaust."],
["A respirator cartridge or filter should be changed according to:",["The employer's respiratory protection program and manufacturer guidance","The color of the containment","The worker's preference alone","A fixed rule of once every decade"],0,"Selection and maintenance must follow the written program and relevant manufacturer instructions."],
["What must the employer provide for required respiratory protection?",["A written respiratory protection program","Only a purchase receipt","Only a verbal promise","Only a storage shelf"],0,"OSHA requires a written, worksite-specific respiratory protection program."]
]);
addQuestions("Work Practices, Procedures, and Disposal",OSHA,[
["What is the first control for fiber release during most ACM removal?",["Wet the material adequately","Use compressed air","Dry scrape rapidly","Remove containment"],0,"Wet methods are a primary engineering and work-practice control."],
["What must a regulated area have at each entrance?",["Warning signs","A food station","Open public access","Only a temperature gauge"],0,"OSHA requires signs at entrances to regulated areas."],
["Who may enter a regulated area during asbestos work?",["Authorized persons","Any visitor","Anyone without PPE","Only building occupants"],0,"Access is restricted to authorized persons."],
["What is prohibited in asbestos regulated areas?",["Eating, drinking, smoking, or chewing","Using properly selected PPE","HEPA vacuuming","Posting signs"],0,"OSHA prohibits eating, drinking, smoking, chewing tobacco or gum, and applying cosmetics in regulated areas."],
["Where should protective clothing contaminated with asbestos be removed?",["In the equipment room or designated decontamination area","In a public hallway","At home","In the employee's vehicle"],0,"Decontamination facilities are intended to prevent contamination leaving the regulated area."],
["How should asbestos waste be stored and transported?",["In sealed, labeled, impermeable containers","Loose in an open truck","In unsealed cardboard","Mixed into ordinary office waste"],0,"OSHA requires asbestos waste and contaminated clothing to be placed in sealed, labeled, impermeable containers."],
["Which cleaning technique is allowed for asbestos-contaminated surfaces?",["HEPA vacuuming","Dry sweeping","Compressed-air blowing","High-speed wire brushing"],0,"HEPA vacuuming is an accepted cleanup method."],
["When may compressed air be used to remove asbestos dust?",["Only with an enclosed ventilation system that captures the dust","Whenever it is faster","Whenever a worker wears gloves","During final cleaning"],0,"OSHA generally prohibits compressed-air cleaning unless used with ventilation that captures the dust cloud."],
["Why must workers use decontamination procedures when leaving Class I regulated areas?",["To avoid carrying asbestos into clean areas","To improve the room's appearance","To increase production","To replace waste packaging"],0,"Decontamination limits transfer of asbestos contamination."],
["For Class I work, the competent person must inspect the worksite:",["At least once during each work shift","Only after completion","Once per month","Only when asked by an inspector"],0,"OSHA specifies competent-person inspections at least once during each shift for Class I work."],
["If a negative-pressure enclosure loses pressure during removal, what should the supervisor do?",["Stop and restore the enclosure controls","Open doors to increase airflow","Ignore the reading","Remove warning signs"],0,"A failure of enclosure pressure calls for corrective action before continuing uncontrolled work."],
["When asbestos-containing floor tile is removed as Class II work, OSHA generally requires it to be:",["Removed intact where feasible","Ground to powder","Dry sanded","Broken into small pieces intentionally"],0,"Class II floor tile methods emphasize intact removal and prohibit aggressive techniques."],
["What is the purpose of a glove bag for eligible small TSI jobs?",["To isolate the disturbance and contain released fibers","To substitute for all worker training","To hold drinking water","To provide building ventilation"],0,"A glove bag provides local containment for appropriate work when used under required procedures."],
["What should happen to a glove bag before it is removed from the work area?",["The contained material and bag must be handled without releasing fibers","It should be opened to dry","It should be shaken outdoors","It should be reused indefinitely"],0,"Glove-bag waste handling must prevent fiber release."],
["How does OSHA's construction asbestos rule treat dry sweeping of ACM dust and debris?",["It is prohibited","It is required after HEPA vacuuming","It is allowed if the job is small","It is required during final cleaning"],0,"OSHA prohibits dry sweeping, shoveling, and other dry cleanup of dust and debris containing ACM or PACM."],
["What is the main purpose of a critical barrier?",["Seal openings between the work area and adjacent spaces","Hold spare tools","Replace air monitoring","Dry the ACM"],0,"Critical barriers help isolate the regulated work area."],
["Why should removed ACM be bagged promptly?",["To minimize opportunities for fiber release and migration","To avoid using labels","To make it dry","To avoid disposal records"],0,"Prompt containment reduces the chance of release while waste is handled."]
]);
addQuestions("Testing Methodologies",OSHA,[
["The OSHA asbestos PEL is measured as:",["An eight-hour time-weighted average","A five-second peak","A weekly temperature average","An annual dust weight"],0,"The permissible exposure limit is an eight-hour TWA."],
["The OSHA excursion limit is averaged over:",["30 minutes","Eight hours","One year","Two seconds"],0,"The excursion limit is a 30-minute average."],
["What should an employer do after exposure monitoring shows a worker above the PEL?",["Notify the affected worker of the result and corrective action","Keep the result secret","Stop all recordkeeping","Assume the respirator eliminates other controls"],0,"OSHA requires notice to affected employees and identification of corrective action when levels exceed a limit."],
["Where is a representative personal air sample collected?",["Near the worker's breathing zone","In the supervisor's office","Outside the building only","At the waste landfill"],0,"Personal exposure sampling reflects air in the worker's breathing zone."],
["What does a negative exposure assessment support?",["A documented conclusion that expected exposures will be below both limits","A claim that the building contains no asbestos","A waiver of all training","A permanent exemption from every rule"],0,"OSHA defines a negative exposure assessment for a specific operation based on evidence exposures will remain below the PEL and excursion limit."],
["Who must perform exposure monitoring under OSHA's construction asbestos rule?",["The employer","Only the waste hauler","Only the building owner","Only the worker's family"],0,"The employer is responsible for required exposure monitoring."],
["Why do results from one task not automatically establish exposure for a different task?",["Conditions and disturbance methods may differ","Asbestos has a fixed concentration everywhere","Air sampling is always invalid","Only humidity determines exposure"],0,"Exposure assessments must represent the operation and conditions."],
["What does PCM count in a standard airborne asbestos analysis?",["Fibers meeting specified counting criteria","Each asbestos mineral's chemical formula","Only visible chunks of insulation","The mass of the whole waste bag"],0,"Phase-contrast microscopy counts fibers using specified criteria; it does not identify mineral type by itself."]
]);
addQuestions("Additional Safety Hazards",OSHA,[
["What conventional hazard can wet asbestos removal increase?",["Electrical shock","Ultraviolet exposure","Radiation","Lightning indoors"],0,"Water near electrical equipment requires electrical hazard controls."],
["Why might an asbestos worker need a heat-stress plan?",["Protective clothing and respirators can increase heat burden","Wet methods eliminate body heat","HEPA filters heat the body directly","Asbestos fibers cool the body"],0,"The physical burden of PPE can contribute to heat stress."],
["Before working above a ceiling, a supervisor should evaluate:",["Fall and structural hazards","Only paint color","Only examination scores","Only room acoustics"],0,"Asbestos work can expose workers to falls and structural hazards."],
["What should a supervisor assess before assigning work in a confined space?",["Entry hazards and applicable confined-space requirements","Only the size of the asbestos bag","Only the weather forecast","Only whether the door is painted"],0,"Confined-space conditions can present atmospheric and rescue hazards beyond asbestos."]
]);
addQuestions("Regulations",NJ,[
["Which NJ agency issues asbestos worker and supervisor permits?",["Department of Labor and Workforce Development","Motor Vehicle Commission","Department of Banking","Local library"],0,"NJ LWD issues performance permits."],
["Which NJ agency certifies asbestos training courses and approves the examination?",["Department of Health","Motor Vehicle Commission","County tax board","State police only"],0,"NJDOH oversees course certification and the approved examination."],
["Under NJ's Asbestos Control and Licensing Act, an employer license is:",["Nontransferable","Transferable to any subcontractor","Good indefinitely","A substitute for each worker permit"],0,"The statute describes the employer license as nontransferable."],
["Under NJ law, a permitted asbestos employee must keep the permit:",["On their person and available for inspection","Only in a home file","Only with the building owner","Only in the waste vehicle"],0,"The permit must be carried and available for inspection."],
["How long are NJ asbestos employer licenses and worker/supervisor permits generally valid?",["12 months","Five years","One week","Indefinitely"],0,"The Act provides a 12-month validity period."],
["A licensed NJ asbestos employer must post at the site:",["A sign stating licensed by New Jersey for asbestos work","A worker's private medical chart","The customer's credit card","An exam answer key"],0,"The Act requires a readily visible licensed-for-asbestos-work sign."],
["What must a contractor generally verify before assigning asbestos work in NJ?",["Required employer license and personnel permits","Only vehicle registration","Only a verbal promise","Only project square footage"],0,"New Jersey's licensing and permitting requirements apply before covered work."]
]);
addQuestions("Legal Considerations",NJ,[
["Knowingly submitting false information on an NJ asbestos permit application can lead to:",["Criminal penalties","Automatic approval","Only a new form","No consequence if corrected later"],0,"The Act identifies knowingly false or misleading application information as a violation with criminal consequences."],
["Can an NJ asbestos employer license simply be loaned to another company?",["No; it is nontransferable","Yes, for one day","Yes, if the job is small","Yes, if the supervisor agrees"],0,"Employer licenses are nontransferable."],
["Who may inspect asbestos licenses and permits under the NJ Act?",["Authorized state enforcement representatives","Only the worker's relatives","Only the building's realtor","Only the waste landfill"],0,"Required credentials must be available for inspection by authorized representatives."],
["An employee who reports an asbestos violation to NJ enforcement agencies is protected against:",["Employer discrimination or sanctions for the complaint","All future work requirements","Every possible job reassignment","All tax obligations"],0,"The Act prohibits discrimination or sanctions against an employee who complains or cooperates with enforcement."],
["A person who believes the NJ Asbestos Control and Licensing Act was violated may:",["File a citizen complaint with the responsible commissioner","Issue a state permit","Cancel all inspections","Change the law unilaterally"],0,"The Act provides a citizen complaint process."],
["Why should a supervisor preserve air-monitoring and work records accurately?",["They document required compliance and may be reviewed in enforcement","They can replace licensing","They make asbestos nonhazardous","They allow permit transfer"],0,"Accurate records support compliance and inspection."],
["What is a sound response to a request to backdate an asbestos work record?",["Refuse and record the actual date","Comply if it helps the schedule","Destroy the original record","Ask a worker to sign it instead"],0,"Required compliance records should reflect the actual work and dates."]
]);
addQuestions("Supervisory",OSHA,[
["A competent person under OSHA must have authority to:",["Promptly correct asbestos hazards","Only order supplies","Issue state permits","Ignore exposure results"],0,"A competent person can identify hazards and has authority to take prompt corrective measures."],
["Who supervises Class I asbestos work under OSHA?",["A designated competent person","Any visitor","Only the waste truck driver","Only the building receptionist"],0,"Class I work must be supervised by a competent person."],
["Before starting removal, what should a supervisor confirm?",["Controls, worker training, PPE, and regulated area are ready","Only the project invoice","Only the weather","Only the owner's preferred paint"],0,"Supervision includes ensuring required controls and worker protections are in place."],
["If a worker's respirator seal cannot be maintained, the supervisor should:",["Keep the worker out of work requiring that respirator until corrected","Let the worker continue with no change","Remove warning signs","Increase dry sweeping"],0,"Required respiratory protection must function properly before exposure."],
["When conditions change from the exposure assessment, the supervisor should:",["Reevaluate exposure and controls","Assume the old assessment remains representative","Delete earlier monitoring","Stop documenting the job"],0,"Assessments must represent actual operations and conditions."]
]);

// Scenario-based expansion added September 2026. These are original practice
// items based on the linked public rules, not questions from the NJ examination.
addQuestions("General Topics Related to Asbestos",OSHA,[
["A contractor finds resilient flooring in a building constructed in 1978. Before treating it as non-asbestos, what is required?",["A determination that rebuts the PACM presumption","A visual check showing the floor is intact","The building owner's verbal assurance","A negative mold test"],0,"OSHA treats resilient flooring material installed no later than 1980 as presumed asbestos-containing material unless the presumption is rebutted in accordance with the standard."],
["Which description best matches friable asbestos-containing material?",["Material that can be crumbled, pulverized, or reduced to powder by hand pressure when dry","Any material painted white","Only material containing more than 50 percent asbestos","Any material located outdoors"],0,"Friability describes whether dry material can be crumbled, pulverized, or reduced to powder by hand pressure." ]
]);

addQuestions("Health and Medical Considerations",OSHA,[
["An employee performs Class III asbestos work on 35 days during the year, with exposures below the PEL each day. Which statement is correct?",["The 30-day trigger can still require medical surveillance","Medical surveillance applies only above the excursion limit","The employee is exempt because the work is Class III","Only a chest X-ray chosen by the supervisor is required"],0,"OSHA's medical-surveillance trigger includes employees engaged in Class I, II, or III work for a combined total of 30 or more days per year, subject to the standard's counting provision."],
["Who determines whether an employee is medically able to use a respirator?",["A physician or other licensed health care professional","The project supervisor alone","The building owner","The respirator salesperson"],0,"The respiratory protection standard assigns the medical evaluation to a physician or other licensed health care professional."],
["Why must asbestos exposure records and medical-surveillance records be kept separately and accurately?",["They document different aspects of exposure and worker health and have different retention requirements","They are interchangeable forms","Only medical records may be inspected","Both may be discarded when a project ends"],0,"Exposure records document airborne exposure, while confidential medical records document health surveillance; OSHA assigns specific access and retention requirements to each." ]
]);

addQuestions("Personal Protective and Other Equipment",RESP,[
["A worker passes a fit test with one make, model, style, and size of tight-fitting respirator. May the worker switch to a different facepiece without another fit test?",["No; the employee must be fit tested with the facepiece that will be used","Yes, if both respirators are the same color","Yes, for any facepiece from the same manufacturer","Yes, if a user seal check is performed"],0,"Fit testing is specific to the same make, model, style, and size of respirator that the employee will use."],
["During asbestos work, a worker detects leakage around a tight-fitting facepiece. What should happen first?",["Leave the respirator-use area and correct the problem","Tighten the straps while continuing removal","Ignore it until the next scheduled break","Cover the leak with tape"],0,"A worker must leave the respirator-use area when leakage is detected and may return only after the respirator problem is corrected."],
["What filter efficiency does OSHA require for powered and non-powered air-purifying respirators used for asbestos?",["HEPA filtration","A nuisance-dust filter","An organic-vapor cartridge alone","No filter when wet methods are used"],0,"OSHA requires high-efficiency filters for powered and non-powered air-purifying respirators used for asbestos exposure." ]
]);

addQuestions("Work Practices, Procedures, and Disposal",OSHA,[
["A crew plans to remove asbestos-containing roofing material using a power cutter. Which control is required for the cutting machine?",["A HEPA-filtered dust collector or equivalent control","A household fan aimed at the operator","Compressed air directed at the blade","No control if the work is outdoors"],0,"For specified Class II roofing work, cutting machines must be continuously misted or used with a HEPA-filtered dust collector, depending on the operation described by the standard."],
["During Class I work involving more than 25 linear or 10 square feet of TSI or surfacing material, which setup is generally required unless an allowed alternative is used?",["A negative-pressure enclosure or another permitted control method","Only caution tape around the debris","Natural ventilation through open windows","A positive-pressure work area"],0,"OSHA requires a negative-pressure enclosure for larger Class I work unless another control method specifically permitted by the standard is used."],
["What should be done with impermeable dropcloths used beneath certain Class II removal operations?",["Keep them in place until they are cleaned with a HEPA vacuum or otherwise disposed of properly","Shake them outdoors for reuse","Dry sweep them at the end of the shift","Move them into an occupied area to fold them"],0,"Dropcloths used to capture asbestos debris must be cleaned with a HEPA vacuum or disposed of in a manner that prevents fiber release."],
["A supervisor wants employees to take contaminated protective clothing home for washing. Is that acceptable?",["No; the employer must ensure laundering is performed without releasing asbestos and inform the launderer of the hazard","Yes, if clothing is placed in a paper bag","Yes, if the employee lives nearby","Yes, for clothing worn less than one hour"],0,"Contaminated work clothing may not be taken home for ordinary laundering; the employer must control handling and communicate the asbestos hazard to whoever launders it."],
["When a waste bag's exterior becomes contaminated inside the regulated area, what is the best action before it leaves containment?",["Clean it or place it into a clean impermeable second container","Carry it directly through occupied space","Puncture it to release trapped air","Leave it open until the material dries"],0,"Waste containers must be handled so their exteriors do not spread contamination; cleaning or controlled double-container handling prevents fiber migration."],
["Why should HVAC openings in or serving an asbestos work area be isolated when required by the work plan?",["To prevent fibers from entering the ventilation system and spreading","To increase positive pressure","To dry removed ACM faster","To replace required respiratory protection"],0,"Isolating ventilation pathways helps keep asbestos fibers from migrating to other building areas." ]
]);

addQuestions("Testing Methodologies",OSHA,[
["Initial exposure monitoring may be omitted only when the employer has made what kind of determination for the operation?",["A valid negative exposure assessment","A visual determination that dust is low","A promise to use respirators","A final-clearance sample before work begins"],0,"A valid negative exposure assessment based on objective data or representative monitoring can satisfy the standard's conditions for avoiding initial monitoring."],
["If employee exposure may reasonably exceed the excursion limit during a short high-dust task, which sampling approach is most relevant?",["A 30-minute breathing-zone sample representing the highest expected exposure","Only an eight-hour area sample in a hallway","A bulk sample of the removed material","A five-minute temperature reading"],0,"The excursion limit is evaluated with a 30-minute employee breathing-zone sample representing the employee's highest expected exposure." ]
]);

addQuestions("Additional Safety Hazards",OSHA,[
["Wet removal is planned near energized wiring. What is the supervisor's best approach?",["Have the electrical hazard evaluated and de-energize or protect the system as required before wet work","Use extra water to cool the wiring","Rely on rubber gloves alone","Ignore the wiring because asbestos is the primary hazard"],0,"Wet methods can increase shock risk, so electrical hazards must be controlled as part of pre-job planning."],
["A worker in full protective clothing becomes confused, unsteady, and stops sweating in a hot containment. What should the supervisor do?",["Treat it as a medical emergency, remove the worker from heat, and obtain emergency help","Have the worker finish the waste bag first","Give the worker a tighter respirator","Wait until the scheduled lunch break"],0,"Confusion and loss of coordination during heat exposure can indicate severe heat illness requiring immediate emergency action." ]
]);

addQuestions("Regulations",EPA,[
["Under the asbestos NESHAP, who must thoroughly inspect an affected facility for asbestos before a demolition or renovation begins?",["The owner or operator of the demolition or renovation activity","Only the waste landfill","Only the local fire department","Only the building's tenants"],0,"The asbestos NESHAP requires the owner or operator to thoroughly inspect the affected facility or affected part of the facility before regulated demolition or renovation."],
["For a facility demolition in which no asbestos is found, does the federal asbestos NESHAP notification requirement automatically disappear?",["No; qualifying demolitions generally still require notification","Yes; notification is only for projects above the PEL","Yes; a verbal notice to workers replaces it","No, but only schools must notify"],0,"NESHAP demolition notification generally applies even when no asbestos is present, subject to the regulation's scope and limited exceptions."],
["Who is an accredited asbestos project designer under the federal model accreditation framework?",["A person trained and accredited to design response actions for schools or public and commercial buildings","Any worker who has completed one day of awareness training","Only a building owner","Any licensed waste transporter"],0,"EPA's accreditation framework establishes a distinct project-designer discipline for designing asbestos response actions." ]
]);

addQuestions("Legal Considerations",NJ,[
["A supervisor discovers that a required NJ worker permit has expired during an active project. What is the proper response?",["Remove the employee from regulated asbestos work until valid authorization is restored","Allow work through the end of the project","Alter the expiration date on the site copy","Use another employee's permit number"],0,"Personnel performing covered asbestos work must hold current required permits; falsifying or sharing credentials is not an acceptable substitute."],
["Why should a supervisor document a containment failure and the corrective actions taken?",["To create an accurate compliance record and show how the hazard was controlled","To replace required notifications","To prevent inspectors from speaking with workers","To eliminate the need for additional evaluation"],0,"Accurate contemporaneous records support regulatory compliance, exposure evaluation, and accountability for corrective action." ]
]);

addQuestions("Supervisory",OSHA,[
["A worker reports visible debris outside containment. What should the competent person do first?",["Stop or restrict affected work, secure the area, and evaluate and correct the breach","Sweep the debris into a hallway trash can","Wait for final clearance","Ask the worker not to document it"],0,"The competent person must act promptly to identify and correct asbestos hazards and prevent further migration or exposure."],
["A subcontractor proposes a faster removal method that is not covered by the exposure assessment or work plan. What should the supervisor do?",["Pause the change and evaluate the method, exposure, and required controls before authorizing it","Approve it if the subcontractor has used it before","Allow one worker to test it without monitoring","Use it only during lunch breaks"],0,"Changed methods can change exposures and required controls; the competent person must evaluate the conditions before work proceeds." ]
]);

// Personnel decontamination: construction, arrangement, and use.
addQuestions("Work Practices, Procedures, and Disposal",OSHA,[
["What is the correct order of a three-stage personnel decontamination facility when traveling from the clean side toward the asbestos work area?",["Clean room, shower, equipment room, work area","Equipment room, clean room, shower, work area","Shower, equipment room, clean room, work area","Clean room, equipment room, shower, work area"],0,"The clean room is on the uncontaminated side, the shower separates the clean and contaminated rooms, and the equipment room connects toward the regulated work area."],
["When leaving an asbestos work area through a three-stage personnel decontamination facility, what is the correct sequence?",["Equipment room, shower, clean room","Clean room, shower, equipment room","Shower, clean room, equipment room","Equipment room, clean room, shower"],0,"A worker exits the regulated area into the equipment room, passes through the shower, and then enters the clean room."],
["Where should a worker remove contaminated disposable protective clothing when exiting a Class I regulated area?",["In the equipment room","In the clean room","In the parking area","At home"],0,"The equipment room is the contaminated change area used for removing and containing work clothing and equipment."],
["What should a worker generally do with a required respirator while passing from the equipment room into the shower?",["Keep it on until it has been washed and the worker is in the shower","Remove it inside the work area","Hang it in the clean room before showering","Place it outside the regulated area without cleaning it"],0,"OSHA's Class I decontamination procedure keeps the respirator on while the employee enters the shower and requires the employee to wash it before removal."],
["Where are employees' street clothes and uncontaminated personal items kept in a three-stage decontamination facility?",["In the clean room","In the equipment room","Inside containment","In the waste-load-out area"],0,"The clean room is equipped for changing into and out of street clothing and must remain free of asbestos contamination."],
["Why is the shower positioned between the equipment room and the clean room?",["To prevent employees from reaching the clean side without washing off contamination","To increase pressure inside containment","To provide storage for waste bags","To replace the equipment room"],0,"The arrangement forces personnel to pass through the shower between the contaminated and clean sides of the facility."],
["How must a required Class I personnel decontamination area be located in relation to the regulated area?",["Adjacent and connected to it","In a separate building across the property","Inside an occupied lunchroom","Beside the waste landfill"],0,"OSHA requires the decontamination area for covered Class I work to be adjacent and connected to the regulated area."],
["Does OSHA assign one universal minimum floor dimension, such as 3 feet by 3 feet, to every decontamination chamber?",["No; the required arrangement and facilities must be adequate, but OSHA does not give every chamber one universal fixed-foot dimension","Yes; every chamber must always be exactly 3 feet by 3 feet","Yes; only the clean room has a fixed federal dimension","No; because room arrangement is optional"],0,"OSHA specifies the required rooms, connection, equipment, and procedures, while a fixed dimension may instead come from a state rule, contract specification, or site plan."],
["Under OSHA sanitation requirements, what shower capacity is generally required when employees must shower during the same shift?",["At least one shower for each 10 employees of each sex, or numerical fraction thereof","One shower for every 50 employees","Exactly one shower per project","One shower only when more than 100 employees are present"],0,"OSHA's sanitation rule generally requires one shower for each 10 employees of each sex, or numerical fraction thereof, who must shower during the same shift."],
["Which shower provisions are required by OSHA sanitation rules?",["Hot and cold or tepid running water, soap or another cleansing agent, and individual towels","Cold water only and shared towels","A dry changing stall with no water","Only bottled drinking water"],0,"Required showers must provide hot and cold water feeding a common discharge line or tepid running water, cleansing agents, and individual towels."],
["What construction principle is most important at the transition between the decontamination facility and the regulated area?",["Personnel must follow a controlled path that maintains separation between contaminated and clean areas","All doorways should remain fully open","The clean room should share air directly with containment","Workers should be able to bypass the shower during busy periods"],0,"The facility must maintain a controlled clean-to-contaminated transition and prevent asbestos contamination from migrating to clean areas."],
["Before tools or reusable equipment leave the regulated area, what must occur?",["They must be cleaned or appropriately contained so asbestos contamination is not carried outside","They must be dry swept","They must be placed directly in an employee's vehicle","They may leave untreated if they are metal"],0,"Equipment and surfaces must be cleaned with methods such as HEPA vacuuming or wet wiping, or contained when cleaning is not feasible, to prevent fiber release and migration." ]
]);
