// Original practice questions drawn from public rules; no state examination items.
const OSHA="https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.1101";
const NJ="https://www.nj.gov/labor/safetyandhealth/resources-support/laws-regulations/asbestosact.shtml";
const EPA="https://www.ecfr.gov/current/title-40/chapter-I/subchapter-C/part-61/subpart-M";
const NJDOH="https://www.nj.gov/health/ceohs/asbestos/asbestos-workers-supervisors/";
const RESP="https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.134";
function addQuestions(category,source,rows){
  rows.forEach(([q,a,correct,explanation])=>QUESTIONS.push({category,q,a,correct,explanation,source}));
}
addQuestions("General Topics Related to Asbestos",OSHA,[
["Under OSHA's construction asbestos rule, ACM contains asbestos in what amount?",["More than 1%","Exactly 0.1%","Any detectable trace","More than 50%"],0,"OSHA defines asbestos-containing material as material containing more than one percent asbestos."],
["Which material is generally presumed asbestos-containing in a building constructed no later than 1980?",["Thermal system insulation","New fiberglass batts","Modern vinyl windows","Unpainted steel"],0,"OSHA presumes thermal system insulation in buildings constructed no later than 1980 to be asbestos-containing unless rebutted."],
["What does TSI mean in the asbestos construction standard?",["Thermal system insulation","Testing sample interval","Temporary site inspection","Toxic surface inventory"],0,"TSI means thermal system insulation applied to pipes, fittings, boilers, breeching, tanks, ducts, or other components to prevent heat loss or gain."],
["Which task is Class I asbestos work under OSHA?",["Removing surfacing ACM","Removing asbestos floor tile","Repairing ACM without removal","Vacuuming dust without disturbing ACM"],0,"Class I covers removal of thermal system insulation or surfacing ACM and PACM."],
["Which task is typically Class II asbestos work?",["Removing asbestos floor tile","Removing sprayed surfacing ACM","Only inspecting intact insulation","Painting a clean wall"],0,"Class II removal involves ACM other than thermal system insulation or surfacing material."],
["Class III asbestos work is best described as:",["Repair and maintenance that disturb ACM or PACM","All demolition of an asbestos building","Only transport of asbestos waste","Removal of all surfacing insulation"],0,"Class III is repair and maintenance work where ACM or PACM is likely to be disturbed."],
["An aggressive method of disturbing ACM includes:",["Grinding that disintegrates intact material","Carefully wetting intact material","HEPA vacuuming settled dust","Sealing a clean opening"],0,"OSHA defines aggressive methods as sanding, abrading, grinding, or other methods that break, crumble, or disintegrate intact ACM."],
["Amended water is water with:",["A surfactant to improve penetration","Added bleach to kill spores","A dye to label waste","Extra oxygen for ventilation"],0,"A wetting agent helps water penetrate ACM."]
]);
addQuestions("Health and Medical Considerations",OSHA,[
["Which asbestos-related disease is a fibrotic lung disease rather than a cancer?",["Asbestosis","Mesothelioma","Lung carcinoma","Skin melanoma"],0,"Asbestosis is lung fibrosis associated with asbestos exposure."],
["The primary route of occupational asbestos exposure during abatement is:",["Inhalation of airborne fibers","Absorption through intact skin","Exposure to visible light","Ingestion of drinking water only"],0,"Inhalation of airborne asbestos fibers is the main occupational exposure route."],
["Why is a worker's lack of symptoms a poor basis for judging asbestos exposure?",["Disease can have a long latency","Asbestos causes immediate pain in all cases","Symptoms always disappear after one shift","Medical tests cannot identify any condition"],0,"Asbestos-related diseases may take many years to develop."],
["Under OSHA's construction rule, medical surveillance is required for a worker engaged in Class I, II, or III work for at least:",["30 days per year","One day per year","100 days per year","Every calendar day"],0,"The standard lists 30 or more days per year of Class I, II, or III work as one trigger."],
["OSHA medical surveillance for covered asbestos employees must be provided:",["At no cost to the employee","Only if the worker pays half","Only after a positive disease diagnosis","Only at the end of employment"],0,"The employer must provide required medical examinations without cost to the employee."],
["What health topic should asbestos training address?",["Health effects of asbestos exposure","Only project billing","Only landscaping","Only building paint colors"],0,"OSHA training includes health effects of asbestos exposure."],
["When should a supervisor treat airborne asbestos exposure as a hazard?",["Even when fibers cannot be seen","Only when fibers are visible","Only when workers smell asbestos","Only when the room is warm"],0,"Airborne asbestos fibers can be too small to see; visibility does not establish safe exposure."]
 ,["Why does OSHA require a medical determination for a worker assigned to wear a negative-pressure respirator?",["To ensure the worker is physically able to perform the work and use the equipment","To determine the worker's examination score","To replace a fit test","To decide the building's age"],0,"A physician-supervised determination addresses the worker's physical ability to use a negative-pressure respirator safely."]
]);
addQuestions("Personal Protective and Other Equipment",RESP,[
["Before an employee wears a required respirator, the employer must provide:",["A medical evaluation","A respirator color chart","A dust mask of any type","A paid lunch break"],0,"The respiratory protection standard requires medical evaluation before use."],
["A tight-fitting respirator fit test must be performed:",["Before initial use and at least annually","Only after a worker complains","Once in a career","Only for disposable gloves"],0,"OSHA requires fit testing before initial use, when the facepiece changes, and at least annually."],
["Which condition invalidates a tight-fitting respirator seal?",["Facial hair between sealing surface and face","A clean-shaven face","Proper fit testing","A correctly sized facepiece"],0,"Facial hair between the sealing surface and face is prohibited."],
["A user seal check is performed:",["Each time a tight-fitting respirator is put on","Only during annual fit testing","Only after removing the respirator","Only by the building owner"],0,"Each donning requires a user seal check."],
["Can a user seal check replace a fit test?",["No, both have different purposes","Yes, always","Yes, after one month","Only for negative-air machines"],0,"A seal check is not a substitute for formal fit testing."],
["Which feature is essential to an asbestos HEPA vacuum?",["A HEPA filtration system","An ordinary paper dust bag only","A fan that blows debris outward","An open exhaust port"],0,"A HEPA vacuum is used to capture asbestos dust without releasing it through the exhaust."],
["A respirator cartridge or filter should be changed according to:",["The employer's respiratory protection program and manufacturer guidance","The color of the containment","The worker's preference alone","A fixed rule of once every decade"],0,"Selection and maintenance must follow the written program and relevant manufacturer instructions."],
["What must the employer provide for required respiratory protection?",["A written respiratory protection program","Only a purchase receipt","Only a verbal promise","Only a storage shelf"],0,"OSHA requires a written, worksite-specific respiratory protection program."]
]);
addQuestions("Work Practices, Procedures, and Disposal",OSHA,[
["What is the first control for fiber release during most ACM removal?",["Wet the material adequately","Use compressed air","Dry scrape rapidly","Remove containment"],0,"Wet methods are a primary engineering and work-practice control."],
["What must a regulated area have at each entrance?",["Warning signs","A food station","Open public access","Only a temperature gauge"],0,"OSHA requires signs at entrances to regulated areas."],
["Who may enter a regulated area during asbestos work?",["Authorized persons","Any visitor","Anyone without PPE","Only building occupants"],0,"Access is restricted to authorized persons."],
["What is prohibited in asbestos regulated areas?",["Eating, drinking, smoking, or chewing","Using properly selected PPE","HEPA vacuuming","Posting signs"],0,"OSHA prohibits eating, drinking, smoking, chewing tobacco or gum, and applying cosmetics in regulated areas."],
["Where should protective clothing contaminated with asbestos be removed?",["In the equipment room or designated decontamination area","In a public hallway","At home","In the employee's vehicle"],0,"Decontamination facilities are intended to prevent contamination leaving the regulated area."],
["How should asbestos waste be stored and transported?",["In sealed, labeled, impermeable containers","Loose in an open truck","In unsealed cardboard","Mixed into ordinary office waste"],0,"OSHA requires asbestos waste and contaminated clothing to be placed in sealed, labeled, impermeable containers."],
["Which cleaning technique is allowed for asbestos-contaminated surfaces?",["HEPA vacuuming","Dry sweeping","Compressed-air blowing","High-speed wire brushing"],0,"HEPA vacuuming is an accepted cleanup method."],
["When may compressed air be used to remove asbestos dust?",["Only with an enclosed ventilation system that captures the dust","Whenever it is faster","Whenever a worker wears gloves","During final cleaning"],0,"OSHA generally prohibits compressed-air cleaning unless used with ventilation that captures the dust cloud."],
["Why must workers use decontamination procedures when leaving Class I regulated areas?",["To avoid carrying asbestos into clean areas","To improve the room's appearance","To increase production","To replace waste packaging"],0,"Decontamination limits transfer of asbestos contamination."],
["For Class I work, the competent person must inspect the worksite:",["At least once during each work shift","Only after completion","Once per month","Only when asked by an inspector"],0,"OSHA specifies competent-person inspections at least once during each shift for Class I work."],
["If a negative-pressure enclosure loses pressure during removal, what should the supervisor do?",["Stop and restore the enclosure controls","Open doors to increase airflow","Ignore the reading","Remove warning signs"],0,"A failure of enclosure pressure calls for corrective action before continuing uncontrolled work."],
["When asbestos-containing floor tile is removed as Class II work, OSHA generally requires it to be:",["Removed intact where feasible","Ground to powder","Dry sanded","Broken into small pieces intentionally"],0,"Class II floor tile methods emphasize intact removal and prohibit aggressive techniques."],
["What is the purpose of a glove bag for eligible small TSI jobs?",["To isolate the disturbance and contain released fibers","To substitute for all worker training","To hold drinking water","To provide building ventilation"],0,"A glove bag provides local containment for appropriate work when used under required procedures."],
["What should happen to a glove bag before it is removed from the work area?",["The contained material and bag must be handled without releasing fibers","It should be opened to dry","It should be shaken outdoors","It should be reused indefinitely"],0,"Glove-bag waste handling must prevent fiber release."],
["How does OSHA's construction asbestos rule treat dry sweeping of ACM dust and debris?",["It is prohibited","It is required after HEPA vacuuming","It is allowed if the job is small","It is required during final cleaning"],0,"OSHA prohibits dry sweeping, shoveling, and other dry cleanup of dust and debris containing ACM or PACM."],
["What is the main purpose of a critical barrier?",["Seal openings between the work area and adjacent spaces","Hold spare tools","Replace air monitoring","Dry the ACM"],0,"Critical barriers help isolate the regulated work area."],
["Why should removed ACM be bagged promptly?",["To minimize opportunities for fiber release and migration","To avoid using labels","To make it dry","To avoid disposal records"],0,"Prompt containment reduces the chance of release while waste is handled."]
]);
addQuestions("Testing Methodologies",OSHA,[
["The OSHA asbestos PEL is measured as:",["An eight-hour time-weighted average","A five-second peak","A weekly temperature average","An annual dust weight"],0,"The permissible exposure limit is an eight-hour TWA."],
["The OSHA excursion limit is averaged over:",["30 minutes","Eight hours","One year","Two seconds"],0,"The excursion limit is a 30-minute average."],
["What should an employer do after exposure monitoring shows a worker above the PEL?",["Notify the affected worker of the result and corrective action","Keep the result secret","Stop all recordkeeping","Assume the respirator eliminates other controls"],0,"OSHA requires notice to affected employees and identification of corrective action when levels exceed a limit."],
["Where is a representative personal air sample collected?",["Near the worker's breathing zone","In the supervisor's office","Outside the building only","At the waste landfill"],0,"Personal exposure sampling reflects air in the worker's breathing zone."],
["What does a negative exposure assessment support?",["A documented conclusion that expected exposures will be below both limits","A claim that the building contains no asbestos","A waiver of all training","A permanent exemption from every rule"],0,"OSHA defines a negative exposure assessment for a specific operation based on evidence exposures will remain below the PEL and excursion limit."],
["Who must perform exposure monitoring under OSHA's construction asbestos rule?",["The employer","Only the waste hauler","Only the building owner","Only the worker's family"],0,"The employer is responsible for required exposure monitoring."],
["Why do results from one task not automatically establish exposure for a different task?",["Conditions and disturbance methods may differ","Asbestos has a fixed concentration everywhere","Air sampling is always invalid","Only humidity determines exposure"],0,"Exposure assessments must represent the operation and conditions."],
["What does PCM count in a standard airborne asbestos analysis?",["Fibers meeting specified counting criteria","Each asbestos mineral's chemical formula","Only visible chunks of insulation","The mass of the whole waste bag"],0,"Phase-contrast microscopy counts fibers using specified criteria; it does not identify mineral type by itself."]
]);
addQuestions("Additional Safety Hazards",OSHA,[
["What conventional hazard can wet asbestos removal increase?",["Electrical shock","Ultraviolet exposure","Radiation","Lightning indoors"],0,"Water near electrical equipment requires electrical hazard controls."],
["Why might an asbestos worker need a heat-stress plan?",["Protective clothing and respirators can increase heat burden","Wet methods eliminate body heat","HEPA filters heat the body directly","Asbestos fibers cool the body"],0,"The physical burden of PPE can contribute to heat stress."],
["Before working above a ceiling, a supervisor should evaluate:",["Fall and structural hazards","Only paint color","Only examination scores","Only room acoustics"],0,"Asbestos work can expose workers to falls and structural hazards."],
["What should a supervisor assess before assigning work in a confined space?",["Entry hazards and applicable confined-space requirements","Only the size of the asbestos bag","Only the weather forecast","Only whether the door is painted"],0,"Confined-space conditions can present atmospheric and rescue hazards beyond asbestos."]
]);
addQuestions("Regulations",NJ,[
["Which NJ agency issues asbestos worker and supervisor permits?",["Department of Labor and Workforce Development","Motor Vehicle Commission","Department of Banking","Local library"],0,"NJ LWD issues performance permits."],
["Which NJ agency certifies asbestos training courses and approves the examination?",["Department of Health","Motor Vehicle Commission","County tax board","State police only"],0,"NJDOH oversees course certification and the approved examination."],
["Under NJ's Asbestos Control and Licensing Act, an employer license is:",["Nontransferable","Transferable to any subcontractor","Good indefinitely","A substitute for each worker permit"],0,"The statute describes the employer license as nontransferable."],
["Under NJ law, a permitted asbestos employee must keep the permit:",["On their person and available for inspection","Only in a home file","Only with the building owner","Only in the waste vehicle"],0,"The permit must be carried and available for inspection."],
["How long are NJ asbestos employer licenses and worker/supervisor permits generally valid?",["12 months","Five years","One week","Indefinitely"],0,"The Act provides a 12-month validity period."],
["A licensed NJ asbestos employer must post at the site:",["A sign stating licensed by New Jersey for asbestos work","A worker's private medical chart","The customer's credit card","An exam answer key"],0,"The Act requires a readily visible licensed-for-asbestos-work sign."],
["What must a contractor generally verify before assigning asbestos work in NJ?",["Required employer license and personnel permits","Only vehicle registration","Only a verbal promise","Only project square footage"],0,"New Jersey's licensing and permitting requirements apply before covered work."]
]);
addQuestions("Legal Considerations",NJ,[
["Knowingly submitting false information on an NJ asbestos permit application can lead to:",["Criminal penalties","Automatic approval","Only a new form","No consequence if corrected later"],0,"The Act identifies knowingly false or misleading application information as a violation with criminal consequences."],
["Can an NJ asbestos employer license simply be loaned to another company?",["No; it is nontransferable","Yes, for one day","Yes, if the job is small","Yes, if the supervisor agrees"],0,"Employer licenses are nontransferable."],
["Who may inspect asbestos licenses and permits under the NJ Act?",["Authorized state enforcement representatives","Only the worker's relatives","Only the building's realtor","Only the waste landfill"],0,"Required credentials must be available for inspection by authorized representatives."],
["An employee who reports an asbestos violation to NJ enforcement agencies is protected against:",["Employer discrimination or sanctions for the complaint","All future work requirements","Every possible job reassignment","All tax obligations"],0,"The Act prohibits discrimination or sanctions against an employee who complains or cooperates with enforcement."],
["A person who believes the NJ Asbestos Control and Licensing Act was violated may:",["File a citizen complaint with the responsible commissioner","Issue a state permit","Cancel all inspections","Change the law unilaterally"],0,"The Act provides a citizen complaint process."],
["Why should a supervisor preserve air-monitoring and work records accurately?",["They document required compliance and may be reviewed in enforcement","They can replace licensing","They make asbestos nonhazardous","They allow permit transfer"],0,"Accurate records support compliance and inspection."],
["What is a sound response to a request to backdate an asbestos work record?",["Refuse and record the actual date","Comply if it helps the schedule","Destroy the original record","Ask a worker to sign it instead"],0,"Required compliance records should reflect the actual work and dates."]
]);
addQuestions("Supervisory",OSHA,[
["A competent person under OSHA must have authority to:",["Promptly correct asbestos hazards","Only order supplies","Issue state permits","Ignore exposure results"],0,"A competent person can identify hazards and has authority to take prompt corrective measures."],
["Who supervises Class I asbestos work under OSHA?",["A designated competent person","Any visitor","Only the waste truck driver","Only the building receptionist"],0,"Class I work must be supervised by a competent person."],
["Before starting removal, what should a supervisor confirm?",["Controls, worker training, PPE, and regulated area are ready","Only the project invoice","Only the weather","Only the owner's preferred paint"],0,"Supervision includes ensuring required controls and worker protections are in place."],
["If a worker's respirator seal cannot be maintained, the supervisor should:",["Keep the worker out of work requiring that respirator until corrected","Let the worker continue with no change","Remove warning signs","Increase dry sweeping"],0,"Required respiratory protection must function properly before exposure."],
["When conditions change from the exposure assessment, the supervisor should:",["Reevaluate exposure and controls","Assume the old assessment remains representative","Delete earlier monitoring","Stop documenting the job"],0,"Assessments must represent actual operations and conditions."]
]);
